import type { MasterCollections, PersonalFormState } from "../types/personalTypes";

export const PERSONAL_MODULE_CODE = "ADMINISTRACION.PERSONAL";

export const ACTION_CODES = {
  create: "CREAR",
  edit: "EDITAR",
  save: "GUARDAR",
  delete: "ELIMINAR",
  export: "EXPORTAR",
  clear: "LIMPIAR",
} as const;

export const EMPTY_FORM: PersonalFormState = {
  tipoDocumentoId: "",
  numeroDocumento: "",
  apellidoPaterno: "",
  apellidoMaterno: "",
  primerNombre: "",
  segundoNombre: "",
  fechaNacimiento: "",
  edad: "",
  nacionalidad: "",
  hijos: "",
  cantidadHijos: "",
  celular: "",
  correoPersonal: "",
  sexoId: "",
  nivelEstudiosId: "",
  estadoCivilId: "",
  datosExtraEmpleado: "",
  departamento: "",
  provincia: "",
  distrito: "",
  direccion: "",
  referenciaDir: "",
  correoCorporativo: "",
  celularEmergencia: "",
  datosExtraDireccion: "",
  origenId: "",
  referenciaPost: "",
  areaPostId: "",
  cargoPostId: "",
  campaniaPostId: "",
  productoPostId: "",
  fechaPostulacion: "",
  datosExtraPost: "",
  jefeEmpleadoId: "",
  codigoEjecutivo: "",
  codigoDial: "",
  codigoPropio: "",
  generacionId: "",
  jornadaId: "",
  turnoId: "",
  tipoContratoId: "",
  areaId: "",
  cargoId: "",
  tipoProductoId: "",
  fechaIngreso: "",
  bancoId: "",
  numeroCuenta: "",
  fechaInicioContrato: "",
  fechaFinContrato: "",
  empresaId: "",
  sueldo: "",
  fechaCambio: "",
  fechaCese: "",
  datosExtraCont: "",
  estadoId: "",
  subEstadoId: "",
  comentario: "",
  datosExtraRegistro: "",
  parentescoId: "",
  famTipoDocumentoId: "",
  famNumeroDocumento: "",
  famPrimerNombre: "",
  famSegundoNombre: "",
  famApellidoPaterno: "",
  famApellidoMaterno: "",
  famSexoId: "",
  famCelular: "",
  famDatosExtra: "",
  campanias: [],
};

export const EMPTY_MASTERS: MasterCollections = {
  tipoDocumentoItems: [],
  sexoItems: [],
  areaItems: [],
  cargoItems: [],
  estadoItems: [],
  subEstadoItems: [],
  estadoCivilItems: [],
  nivelEstudiosItems: [],
  origenItems: [],
  campaniaItems: [],
  productoItems: [],
  generacionItems: [],
  jornadaItems: [],
  turnoItems: [],
  tipoContratoItems: [],
  bancoItems: [],
  empresaItems: [],
  parentescoItems: [],
};
