export type ListEmpleadosParams = {
  pagina?: number;
  tamanio?: number;
  texto?: string;
  soloActivos?: boolean;
  estadoId?: number;
  areaId?: number;
  cargoId?: number;
};

export type EmpleadoListItem = {
  empleadoId: number;
  tipoDocumentoId?: number | null;
  numeroDocumento?: string | null;
  apellidoPaterno?: string | null;
  apellidoMaterno?: string | null;
  primerNombre?: string | null;
  segundoNombre?: string | null;
  celular?: string | null;
  correoPersonal?: string | null;
  activo: boolean;
  estadoId?: number | null;
  subEstadoId?: number | null;
  areaId?: number | null;
  areaNombre?: string | null;
  cargoId?: number | null;
  cargoNombre?: string | null;
  tipoProductoId?: number | null;
  tipoProductoNombre?: string | null;
  usuarioId?: number | null;
  usuarioLogin?: string | null;
  usuarioActivo?: boolean | null;
  cantidadCampanias?: number | null;
  campaniasNombres?: string | null;
  fechaCreacion: string;
  fechaModificacion?: string | null;
};

export type EmpleadoBasico = {
  empleadoId: number;
  tipoDocumentoId?: number | null;
  numeroDocumento?: string | null;
  apellidoPaterno?: string | null;
  apellidoMaterno?: string | null;
  primerNombre?: string | null;
  segundoNombre?: string | null;
  fechaNacimiento?: string | null;
  edad?: string | null;
  nacionalidad?: string | null;
  hijos?: boolean | null;
  cantidadHijos?: number | null;
  celular?: string | null;
  correoPersonal?: string | null;
  sexoId?: number | null;
  nivelEstudiosId?: number | null;
  estadoCivilId?: number | null;
  activo: boolean;
};

export type EmpleadoDireccion = {
  empleadoDireccionId: number;
  empleadoId: number;
  departamento?: string | null;
  provincia?: string | null;
  distrito?: string | null;
  direccion?: string | null;
  referenciaDir?: string | null;
  correoCorporativo?: string | null;
  celularEmergencia?: string | null;
  activo: boolean;
};

export type EmpleadoContratacion = {
  empleadoContratacionId: number;
  empleadoId: number;
  areaId?: number | null;
  areaNombre?: string | null;
  cargoId?: number | null;
  cargoNombre?: string | null;
  tipoProductoId?: number | null;
  tipoProductoNombre?: string | null;
  tipoContratoId?: number | null;
  tipoContratoNombre?: string | null;
  fechaIngreso?: string | null;
  numeroCuenta?: string | null;
  fechaInicioContrato?: string | null;
  fechaFinContrato?: string | null;
  sueldo?: number | null;
  fechaCambio?: string | null;
  fechaCese?: string | null;
  activo: boolean;
};

export type EmpleadoRegistro = {
  empleadoRegistroId: number;
  empleadoId: number;
  estadoId?: number | null;
  subEstadoId?: number | null;
  comentario?: string | null;
  activo: boolean;
};

export type EmpleadoCompleto = {
  encontrado: boolean;
  empleadoId: number;
  empleado?: EmpleadoBasico | null;
  direccion?: EmpleadoDireccion | null;
  postulacion?: {
    empleadoPostulacionId: number;
    empleadoId: number;
    origenId?: number | null;
    referenciaPost?: string | null;
    areaId?: number | null;
    cargoId?: number | null;
    campaniaId?: number | null;
    productoId?: number | null;
    fechaPostulacion?: string | null;
    activo: boolean;
  } | null;
  contratacion?: EmpleadoContratacion | null;
  registro?: EmpleadoRegistro | null;
  familiares?: Array<{
    familiarId: number;
    empleadoId: number;
    parentescoId?: number | null;
    tipoDocumentoId?: number | null;
    numeroDocumento?: string | null;
    primerNombre?: string | null;
    segundoNombre?: string | null;
    apellidoPaterno?: string | null;
    apellidoMaterno?: string | null;
    sexoId?: number | null;
    celular?: string | null;
    activo: boolean;
  }>;
  campanias?: Array<{
    empleadoCampaniaId: number;
    empleadoId: number;
    campaniaItemMaestroId: number;
    campaniaCodigo?: string | null;
    campaniaNombre?: string | null;
    activo: boolean;
  }>;
};

export type EmpleadoBuscarPorDocumento = {
  encontrado: boolean;
  empleadoId: number;
  tipoDocumentoId?: number | null;
  numeroDocumento?: string | null;
  apellidoPaterno?: string | null;
  apellidoMaterno?: string | null;
  primerNombre?: string | null;
  segundoNombre?: string | null;
  celular?: string | null;
  correoPersonal?: string | null;
  activo: boolean;
  estadoId?: number | null;
  subEstadoId?: number | null;
  areaId?: number | null;
  areaCodigo?: string | null;
  areaNombre?: string | null;
  cargoId?: number | null;
  cargoCodigo?: string | null;
  cargoNombre?: string | null;
  tipoProductoId?: number | null;
  tipoProductoCodigo?: string | null;
  tipoProductoNombre?: string | null;
  jefeEmpleadoId?: number | null;
  usuarioId?: number | null;
  usuarioLogin?: string | null;
  usuarioActivo?: boolean | null;
  cantidadCampanias?: number | null;
  campaniasNombres?: string | null;
  fechaCreacion: string;
  fechaModificacion?: string | null;
  campanias: Array<{
    empleadoCampaniaId: number;
    empleadoId: number;
    campaniaItemMaestroId: number;
    campaniaCodigo?: string | null;
    campaniaNombre?: string | null;
    activo: boolean;
  }>;
};

export type SaveEmpleadoRequest = {
  tipoDocumentoId: number;
  numeroDocumento: string;
  apellidoPaterno?: string | null;
  apellidoMaterno?: string | null;
  primerNombre?: string | null;
  segundoNombre?: string | null;
  fechaNacimiento?: string | null;
  edad?: string | null;
  nacionalidad?: string | null;
  hijos?: boolean | null;
  cantidadHijos?: number | null;
  celular?: string | null;
  correoPersonal?: string | null;
  sexoId?: number | null;
  nivelEstudiosId?: number | null;
  estadoCivilId?: number | null;
  datosExtraEmpleado?: string | null;
  departamento?: string | null;
  provincia?: string | null;
  distrito?: string | null;
  direccion?: string | null;
  referenciaDir?: string | null;
  correoCorporativo?: string | null;
  celularEmergencia?: string | null;
  datosExtraDireccion?: string | null;
  origenId?: number | null;
  referenciaPost?: string | null;
  areaPostId?: number | null;
  cargoPostId?: number | null;
  campaniaPostId?: number | null;
  productoPostId?: number | null;
  fechaPostulacion?: string | null;
  datosExtraPost?: string | null;
  jefeEmpleadoId?: number | null;
  codigoEjecutivo?: string | null;
  codigoDial?: string | null;
  codigoPropio?: string | null;
  generacionId?: number | null;
  jornadaId?: number | null;
  turnoId?: number | null;
  tipoContratoId?: number | null;
  areaId?: number | null;
  cargoId?: number | null;
  tipoProductoId?: number | null;
  fechaIngreso?: string | null;
  bancoId?: number | null;
  numeroCuenta?: string | null;
  fechaInicioContrato?: string | null;
  fechaFinContrato?: string | null;
  empresaId?: number | null;
  sueldo?: number | null;
  fechaCambio?: string | null;
  fechaCese?: string | null;
  datosExtraCont?: string | null;
  estadoId?: number | null;
  subEstadoId?: number | null;
  comentario?: string | null;
  auditorUsuarioId?: number | null;
  datosExtraRegistro?: string | null;
  parentescoId?: number | null;
  famTipoDocumentoId?: number | null;
  famNumeroDocumento?: string | null;
  famPrimerNombre?: string | null;
  famSegundoNombre?: string | null;
  famApellidoPaterno?: string | null;
  famApellidoMaterno?: string | null;
  famSexoId?: number | null;
  famCelular?: string | null;
  famDatosExtra?: string | null;
  campanias: number[];
};

export type SaveEmpleadoResponse = {
  empleadoId: number;
  usuarioId?: number | null;
  estadoCodigo?: string | null;
  subEstadoCodigo?: string | null;
  areaId?: number | null;
  cargoId?: number | null;
  tipoProductoId?: number | null;
  cantidadCampanias: number;
};

export type EmpleadoOperacionResponse = {
  empleadoId: number;
  mensaje: string;
};

export type EmpleadoConsultaDni = {
  numeroDocumento: string;
  nombres?: string | null;
  apellidoPaterno?: string | null;
  apellidoMaterno?: string | null;
  nombreCompleto?: string | null;
};
