import type { AppItemMaestro } from "@/types";

export type ModalTone = "info" | "warning" | "error";
export type FormField = keyof PersonalFormState;
export type DocumentGate = "idle" | "checking" | "existing" | "ready" | "invalid";

export type MasterCollections = {
  tipoDocumentoItems: AppItemMaestro[];
  sexoItems: AppItemMaestro[];
  areaItems: AppItemMaestro[];
  cargoItems: AppItemMaestro[];
  estadoItems: AppItemMaestro[];
  subEstadoItems: AppItemMaestro[];
  estadoCivilItems: AppItemMaestro[];
  nivelEstudiosItems: AppItemMaestro[];
  origenItems: AppItemMaestro[];
  campaniaItems: AppItemMaestro[];
  productoItems: AppItemMaestro[];
  generacionItems: AppItemMaestro[];
  jornadaItems: AppItemMaestro[];
  turnoItems: AppItemMaestro[];
  tipoContratoItems: AppItemMaestro[];
  bancoItems: AppItemMaestro[];
  empresaItems: AppItemMaestro[];
  parentescoItems: AppItemMaestro[];
};

export type PersonalFormState = {
  tipoDocumentoId: string;
  numeroDocumento: string;
  apellidoPaterno: string;
  apellidoMaterno: string;
  primerNombre: string;
  segundoNombre: string;
  fechaNacimiento: string;
  edad: string;
  nacionalidad: string;
  hijos: string;
  cantidadHijos: string;
  celular: string;
  correoPersonal: string;
  sexoId: string;
  nivelEstudiosId: string;
  estadoCivilId: string;
  datosExtraEmpleado: string;
  departamento: string;
  provincia: string;
  distrito: string;
  direccion: string;
  referenciaDir: string;
  correoCorporativo: string;
  celularEmergencia: string;
  datosExtraDireccion: string;
  origenId: string;
  referenciaPost: string;
  areaPostId: string;
  cargoPostId: string;
  campaniaPostId: string;
  productoPostId: string;
  fechaPostulacion: string;
  datosExtraPost: string;
  jefeEmpleadoId: string;
  codigoEjecutivo: string;
  codigoDial: string;
  codigoPropio: string;
  generacionId: string;
  jornadaId: string;
  turnoId: string;
  tipoContratoId: string;
  areaId: string;
  cargoId: string;
  tipoProductoId: string;
  fechaIngreso: string;
  bancoId: string;
  numeroCuenta: string;
  fechaInicioContrato: string;
  fechaFinContrato: string;
  empresaId: string;
  sueldo: string;
  fechaCambio: string;
  fechaCese: string;
  datosExtraCont: string;
  estadoId: string;
  subEstadoId: string;
  comentario: string;
  datosExtraRegistro: string;
  parentescoId: string;
  famTipoDocumentoId: string;
  famNumeroDocumento: string;
  famPrimerNombre: string;
  famSegundoNombre: string;
  famApellidoPaterno: string;
  famApellidoMaterno: string;
  famSexoId: string;
  famCelular: string;
  famDatosExtra: string;
  campanias: string[];
};

export type DocumentKind = "DNI" | "CE" | "OTRO";

export type DocumentMeta = {
  kind: DocumentKind;
  label: string;
  expectedLength: number | null;
  enableLookup: boolean;
};
