export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  profile: "/profile",
  inbox: "/inbox",
  adminPersonal: "/admin/personal",
  adminComisiones: "/admin/comisiones",
  adminPagos: "/admin/pagos",
  adminReportesPersonal: "/admin/reportes-personal",
  tiIngresosSalidas: "/ti/soporte-tecnico/ingresos-salidas",
  tiInventario: "/ti/soporte-tecnico/inventario",
  tiSistemasListas: "/ti/sistemas/listas",
  tiSistemasBases: "/ti/sistemas/bases",
  gerenciaReporteListas: "/gerencia/reporte-listas",
  gerenciaReporteBases: "/gerencia/reporte-bases",
  gerenciaReporteVentas: "/gerencia/reporte-ventas",
  gerenciaReporteGestionPersonal: "/gerencia/reporte-gestion-personal",
  documentosOperativos: "/documentos-operativos",
  goVentasOhTc: "/gestion-operativa/ventas/oh-tc",
  goVentasOhMax: "/gestion-operativa/ventas/oh-max",
  goVentasOhPld: "/gestion-operativa/ventas/oh-pld",
  goVentasSantanderTc: "/gestion-operativa/ventas/santander-tc",
  goVentasSantanderLd: "/gestion-operativa/ventas/santander-ld",
  goVentasCencosudTc: "/gestion-operativa/ventas/cencosud-tc",
  goVentasCencosudLd: "/gestion-operativa/ventas/cencosud-ld",
  goBoOhTc: "/gestion-operativa/back-office/oh-tc",
  goBoOhMax: "/gestion-operativa/back-office/oh-max",
  goBoOhPld: "/gestion-operativa/back-office/oh-pld",
  goBoSantanderTc: "/gestion-operativa/back-office/santander-tc",
  goBoSantanderLd: "/gestion-operativa/back-office/santander-ld",
  goBoCencosudTc: "/gestion-operativa/back-office/cencosud-tc",
  goBoCencosudLd: "/gestion-operativa/back-office/cencosud-ld",
  configuracionMantenimientoTablas: "/configuracion/mantenimiento-tablas",
  configuracionUsuarios: "/configuracion/usuarios",
} as const;

export type AppRoutePath = (typeof ROUTES)[keyof typeof ROUTES];
